export const SETTLEMENT_HAMLET_MAX = 199;
export const SETTLEMENT_VILLAGE_MIN = 200;
export const SETTLEMENT_VILLAGE_MAX = 999;
export const SETTLEMENT_TOWN_MIN = 1000;
export const SETTLEMENT_TOWN_MAX = 4999;
export const SETTLEMENT_CITY_MIN = 5000;
export const SETTLEMENT_EXPAND_THRESHOLD = 1000;
